apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: springbootdemo
        imagePullPolicy: Always
        image: ${{FDDKR_INP_IMAGE_NAME}}:${{FDDKR_INP_IMAGE_TAG}}
        ports:
        - containerPort: 8090
        envFrom:
        - configMapRef:
            name: springboot-demo-config
        - secretRef:
            name: springbootdemo-secret
      imagePullSecrets:
      - name: myregistrykey